ERROR - 2022-02-14 10:53:48 --> Error connecting to the database: pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: Software caused connection abort (0x00002745/10053)
	Is the server running on host &quot;10.8.100.174&quot; and accepting
	TCP/IP connections on port 5432?
CRITICAL - 2022-02-14 10:53:49 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: Software caused connection abort (0x00002745/10053)
	Is the server running on host &quot;10.8.100.174&quot; and accepting
	TCP/IP connections on port 5432?
#0 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\DependenciaController.php(28): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\DependenciaController->index()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DependenciaController))
#7 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-02-14 11:09:20 --> ErrorException: pg_query(): Query failed: ERROR:  operator does not exist: smallint &lt;&gt; boolean
LINE 4: AND &quot;id_usuario&quot; != TRUE
                         ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\Codeigniter\SISIL\app\Validation\UsuarioReglas.php(14): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(292): App\Validation\UsuarioReglas->validateEmailUsuario('william.caldero...', '1', Array, NULL)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('tbx_email_usuar...', 'tbx_email_usuar...', 'william.caldero...', Array, Array)
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#11 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(78): CodeIgniter\Controller->validate(Array)
#12 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#13 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#14 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
ERROR - 2022-02-14 11:11:11 --> ErrorException: pg_query(): Query failed: ERROR:  operator does not exist: smallint &lt;&gt; boolean
LINE 4: AND &quot;id_usuario&quot; != TRUE
                         ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\Codeigniter\SISIL\app\Validation\UsuarioReglas.php(14): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(292): App\Validation\UsuarioReglas->validateEmailUsuario('guillermo.padil...', '2', Array, NULL)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('tbx_email_usuar...', 'tbx_email_usuar...', 'guillermo.padil...', Array, Array)
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#11 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(78): CodeIgniter\Controller->validate(Array)
#12 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('2')
#13 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#14 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2022-02-14 11:11:11 --> pg_query(): Query failed: ERROR:  operator does not exist: smallint &lt;&gt; boolean
LINE 4: AND &quot;id_usuario&quot; != TRUE
                         ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\Codeigniter\SISIL\app\Validation\UsuarioReglas.php(14): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(292): App\Validation\UsuarioReglas->validateEmailUsuario('guillermo.padil...', '2', Array, NULL)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('tbx_email_usuar...', 'tbx_email_usuar...', 'guillermo.padil...', Array, Array)
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#11 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(78): CodeIgniter\Controller->validate(Array)
#12 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('2')
#13 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#14 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2022-02-14 11:11:12 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-02-14 11:14:43 --> ErrorException: pg_query(): Query failed: ERROR:  operator does not exist: smallint &lt;&gt; boolean
LINE 4: AND &quot;id_usuario&quot; != TRUE
                         ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\Codeigniter\SISIL\app\Validation\UsuarioReglas.php(14): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(292): App\Validation\UsuarioReglas->validateEmailUsuario('william.caldero...', '1', Array, NULL)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('tbx_email_usuar...', 'tbx_email_usuar...', 'william.caldero...', Array, Array)
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#11 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(78): CodeIgniter\Controller->validate(Array)
#12 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#13 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#14 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2022-02-14 11:14:58 --> pg_query(): Query failed: ERROR:  operator does not exist: smallint &lt;&gt; boolean
LINE 4: AND &quot;id_usuario&quot; != TRUE
                         ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\Codeigniter\SISIL\app\Validation\UsuarioReglas.php(14): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(292): App\Validation\UsuarioReglas->validateEmailUsuario('william.caldero...', '1', Array, NULL)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('tbx_email_usuar...', 'tbx_email_usuar...', 'william.caldero...', Array, Array)
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#11 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(78): CodeIgniter\Controller->validate(Array)
#12 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#13 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#14 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2022-02-14 11:14:58 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-02-14 11:17:29 --> ErrorException: pg_query(): Query failed: ERROR:  operator does not exist: smallint &lt;&gt; boolean
LINE 4: AND &quot;id_usuario&quot; != TRUE
                         ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\Codeigniter\SISIL\app\Validation\UsuarioReglas.php(14): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(292): App\Validation\UsuarioReglas->validateEmailUsuario('william.caldero...', '1', Array, NULL)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('tbx_email_usuar...', 'tbx_email_usuar...', 'william.caldero...', Array, Array)
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#11 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(78): CodeIgniter\Controller->validate(Array)
#12 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#13 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#14 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#16 {main}
ERROR - 2022-02-14 11:38:31 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for type smallint: &quot;WILLIAM LUIS&quot;
LINE 1: ...', &quot;telefono&quot; = '5532202731', &quot;estatus_usuario&quot; = 'WILLIAM L...
                                                             ^ in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'UPDATE "t_usuar...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "t_usuar...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "t_usuar...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "t_usuar...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(99): CodeIgniter\Model->update('1', Array)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-02-14 11:38:32 --> pg_query(): Query failed: ERROR:  invalid input syntax for type smallint: &quot;WILLIAM LUIS&quot;
LINE 1: ...', &quot;telefono&quot; = '5532202731', &quot;estatus_usuario&quot; = 'WILLIAM L...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'UPDATE "t_usuar...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "t_usuar...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "t_usuar...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "t_usuar...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(99): CodeIgniter\Model->update('1', Array)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-02-14 11:38:32 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-02-14 11:39:24 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for type smallint: &quot;WILLIAM&quot;
LINE 1: ...', &quot;telefono&quot; = '3256854512', &quot;estatus_usuario&quot; = 'WILLIAM',...
                                                             ^ in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'UPDATE "t_usuar...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "t_usuar...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "t_usuar...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "t_usuar...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(99): CodeIgniter\Model->update('1', Array)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-02-14 11:39:28 --> pg_query(): Query failed: ERROR:  invalid input syntax for type smallint: &quot;WILLIAM&quot;
LINE 1: ...', &quot;telefono&quot; = '3256854512', &quot;estatus_usuario&quot; = 'WILLIAM',...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'UPDATE "t_usuar...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "t_usuar...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "t_usuar...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "t_usuar...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(99): CodeIgniter\Model->update('1', Array)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-02-14 11:39:31 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-02-14 11:40:59 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for type smallint: &quot;WILLIAM&quot;
LINE 1: ...', &quot;telefono&quot; = '3256854512', &quot;estatus_usuario&quot; = 'WILLIAM',...
                                                             ^ in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'UPDATE "t_usuar...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "t_usuar...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "t_usuar...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "t_usuar...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(99): CodeIgniter\Model->update('1', Array)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-02-14 11:47:54 --> pg_query(): Query failed: ERROR:  invalid input syntax for type smallint: &quot;WILLIAM&quot;
LINE 1: ...', &quot;telefono&quot; = '3256854512', &quot;estatus_usuario&quot; = 'WILLIAM',...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'UPDATE "t_usuar...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "t_usuar...')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "t_usuar...')
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "t_usuar...', Array, false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(99): CodeIgniter\Model->update('1', Array)
#9 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#10 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-02-14 11:47:54 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-14 16:47:21 --> Undefined property: Config\WebConfig::$MailPassword
#0 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(138): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 138, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(103): App\Controllers\UsuarioController->EnviarCorreo('william.caldero...', 'Hola mundo', 'Correo de prueb...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-02-14 16:48:38 --> Email: sendWithSmtp throwed fsockopen(): unable to connect to ssl://10.1.41.11:25 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
)
ERROR - 2022-02-14 17:01:10 --> Email: sendWithSmtp throwed fsockopen(): unable to connect to ssl://10.1.41.11:25 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
)
CRITICAL - 2022-02-14 17:01:34 --> Undefined property: App\Controllers\UsuarioController::$email
#0 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(163): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 163, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(107): App\Controllers\UsuarioController->EnviarCorreo('william.caldero...', 'Hola mundo', 'Correo de prueb...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-02-14 17:06:04 --> Email: sendWithSmtp throwed fsockopen(): unable to connect to ssl://10.1.41.11:25 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
)
CRITICAL - 2022-02-14 17:06:15 --> Undefined property: App\Controllers\UsuarioController::$email
#0 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(163): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 163, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(107): App\Controllers\UsuarioController->EnviarCorreo('william.caldero...', 'Hola mundo', 'Correo de prueb...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-02-14 17:12:25 --> Undefined property: App\Controllers\UsuarioController::$email
#0 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(166): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 166, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(107): App\Controllers\UsuarioController->EnviarCorreo('william.caldero...', 'Hola mundo', 'Correo de prueb...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-02-14 17:20:24 --> Email: sendWithSmtp throwed fsockopen(): unable to connect to ssl://10.1.41.11:25 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
)
CRITICAL - 2022-02-14 17:20:24 --> Undefined property: App\Controllers\UsuarioController::$email
#0 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(160): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 160, Array)
#1 C:\xampp\htdocs\Codeigniter\SISIL\app\Controllers\UsuarioController.php(107): App\Controllers\UsuarioController->EnviarCorreo('william.caldero...', 'Hola mundo', 'Correo de prueb...')
#2 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(825): App\Controllers\UsuarioController->AgregarActualizarUsuario('1')
#3 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#4 C:\xampp\htdocs\Codeigniter\SISIL\vendor\codeigniter4\framework\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Codeigniter\SISIL\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-02-14 17:21:21 --> Email: sendWithSmtp throwed fsockopen(): unable to connect to ssl://10.1.41.11:25 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
)
ERROR - 2022-02-14 17:22:55 --> Email: sendWithSmtp throwed fsockopen(): unable to connect to ssl://10.1.41.11:25 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
)
ERROR - 2022-02-14 18:05:38 --> Email: sendWithSmtp throwed fsockopen(): unable to connect to ssl://10.1.41.11:25 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
)
ERROR - 2022-02-14 18:09:29 --> Email: sendWithSmtp throwed fsockopen(): unable to connect to ssl://10.1.40.11:25 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
)
ERROR - 2022-02-14 18:11:34 --> Email: sendWithSmtp throwed fsockopen(): unable to connect to ssl://10.1.40.11:25 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
)
